# Generated by Django 2.0.5 on 2018-07-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_drive', 'Can drive'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol'))},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mooo',
        ),
    ]
