# Generated by Django 2.0.5 on 2018-07-03 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationmodel',
            name='lastOrderToday',
        ),
        migrations.AddField(
            model_name='configurationmodel',
            name='lastOrderDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
