# Generated by Django 2.0.5 on 2018-07-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180703_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstOrderIDToday', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('WT', 'Waiting'), ('RJ', 'Rejected'), ('CM', 'Confirmed'), ('RD', 'Ready'), ('DV', 'Delivered')], default='WT', max_length=2),
        ),
        migrations.AddField(
            model_name='configurationmodel',
            name='lastOrderToday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Order'),
        ),
    ]
