# Generated by Django 2.0.5 on 2018-07-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180713_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_add_order', 'Can add order'), ('can_see_orders', 'Can see orders'), ('can_change_salary', 'Can change salary'), ('can_see_activities', 'Can see activities'), ('can_add_payments', 'Can add payments'), ('can_change_menu', 'Can change menu'), ('can_request_supplies', 'Can request supplies'))},
        ),
    ]
