# Generated by Django 2.0.5 on 2018-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180701_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobTitle',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
