# Generated by Django 2.0.5 on 2018-07-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jobTitle',
            field=models.CharField(default='مدیر', max_length=64),
        ),
    ]
