# Generated by Django 2.0.5 on 2018-07-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180704_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
