# Generated by Django 2.0.4 on 2018-07-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180704_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_menu',
        ),
        migrations.AddField(
            model_name='activity',
            name='moneyTrade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default=True, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='inMenu',
            field=models.BooleanField(default=True),
        ),
    ]
