# Generated by Django 2.0.5 on 2018-07-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180704_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='in_menu',
            new_name='inMenu',
        ),
        migrations.AddField(
            model_name='activity',
            name='moneyTrade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default=True, max_length=128),
            preserve_default=False,
        ),
    ]
